# Generated by Django 3.2 on 2021-04-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPlayer', models.TextField(max_length=20)),
                ('namePlayer', models.TextField(max_length=100)),
                ('agePlayer', models.IntegerField(max_length=100)),
            ],
        ),
    ]
