# Generated by Django 3.2.4 on 2021-06-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oriented',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientedType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_name', models.CharField(max_length=20)),
                ('personName', models.CharField(max_length=20)),
                ('interested', models.ManyToManyField(to='server.Interest')),
                ('oriented', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.oriented')),
            ],
        ),
        migrations.CreateModel(
            name='SwipePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('fromPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_person', to='server.person')),
                ('toPerson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_person', to='server.person')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='swipePerson',
            field=models.ManyToManyField(through='server.SwipePerson', to='server.Person'),
        ),
    ]
