# Generated by Django 3.2.4 on 2021-06-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.TextField(null=True),
        ),
    ]
