# Generated by Django 3.2.4 on 2021-06-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('fromPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to='server.person')),
                ('toPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person', to='server.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='swipePerson',
            field=models.ManyToManyField(through='server.SwipePerson', to='server.Person'),
        ),
    ]
