# Generated by Django 3.2.4 on 2021-06-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_person_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='personName',
        ),
    ]
